image: docker:19

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE: "rove-3js-app"
  DEPLOYMENT: "deployment"
  PROJECT_ID: "moshwithme"
  GCP_KEY: "$MOSHWITHME_GCP_SA_KEY"
  IMAGE_TAG: "prod-${CI_COMMIT_SHORT_SHA}"
  LATEST_IMAGE_TAG: "latest"
  IMAGE_URL: "gcr.io/${PROJECT_ID}/${IMAGE}:${IMAGE_TAG}"
  LATEST_IMAGE_URL: "gcr.io/${PROJECT_ID}/${IMAGE}:${LATEST_IMAGE_TAG}"
.config:
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      variables:
        IMAGE_TAG: "main-${CI_COMMIT_SHORT_SHA}"

# Build template
.build: &build
  stage: build
  before_script:
    - echo "$GCP_KEY" | base64 -d | docker login -u _json_key --password-stdin https://gcr.io
    - echo "bulding image $LATEST_IMAGE_URL & $IMAGE_URL"
  script:
    - docker pull $LATEST_IMAGE_URL || true
    - docker build --cache-from $LATEST_IMAGE_URL --tag $IMAGE_URL --tag $LATEST_IMAGE_URL .
    - docker push $IMAGE_URL
    - docker push $LATEST_IMAGE_URL
  tags:
    - high-cpu


build:
  <<: *build
  extends: .config

